# Site settings
title: molily
email: molily@mailbox.org
description: "HTML, CSS, JavaScript and web development"
keywords: "HTML, CSS, JavaScript, web design, web development, browsers, web standards"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://molily.de"
permalink: /:title/

# Build settings
host: 0.0.0.0
markdown: kramdown

sass:
  style: compressed
