# Site settings
title: molily
email: zapperlott@gmail.com
description: "molily über HTML, CSS, JavaScript und Webentwicklung"
keywords: "HTML, CSS, JavaScript, Webdesign, Webentwicklung, Browser, Webstandards"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://molily.de"
permalink: /:title/
twitter_username: molily
github_username:  molily

# Build settings
host: 0.0.0.0
markdown: kramdown

sass:
  style: compressed
